name: WezTerm Windows Alt Icon Builds

on:
  schedule:
    - cron: "0 5 * * *"

  push:
    branches:
      - main
    paths:
      - "/alt-icons/*"

  workflow_dispatch:
    inputs:
      debugging:
        type: boolean
        required: false
        default: false

jobs:
  get-wezterm:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get-wezterm-latest.outputs.version }}
    steps:

      - name: Get WezTerm Latest Release Version Tag
        id: get-wezterm-latest
        run: |
          version=$(
            curl -s "https://api.github.com/repos/wezterm/wezterm/releases/latest" \
              | jq -r '.tag_name'
          )

          # Output the tag name using the new syntax
          echo "version=$version" >> $GITHUB_OUTPUT

      - name: Set release tag variable
        id: vars
        run: |
          echo "release_tag=${{ steps.get-wezterm-latest.outputs.version }}-alt-icons" >> $GITHUB_OUTPUT

      - name: Get WezTerm Windows Zip
        id: get-wezterm-zip
        run: |
          export wezterm_version="${{ steps.get-wezterm-latest.outputs.version }}"

          echo "wezterm_version=$wezterm_version"

          export wezterm_folder="WezTerm-windows-${wezterm_version}"
          echo "wezterm_folder=$wezterm_folder"

          export url="https://github.com/wezterm/wezterm/releases/download/${wezterm_version}/${wezterm_folder}.zip"
          echo "url=$url"

          curl -Lso temp.zip "$url"

          unzip temp.zip
          mv $wezterm_folder wezterm
          rm temp.zip

      - name: Debug version capture step one
        run: |
          echo "version: ${{ steps.get-wezterm-latest.outputs.version }}"

      - uses: actions/upload-artifact@v4
        with:
          name: wezterm.zip
          path: wezterm
          retention-days: 2

  icon-matrix:
    needs: get-wezterm
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: "Checkout Local Repo"
        uses: actions/checkout@v4

      - name: Generate Icon Matrix
        id: set-matrix
        run: python3 scripts/generate_icon_matrix.py

      - id: upload-alt-icons
        uses: actions/upload-artifact@v4
        with:
          name: alt-icons.zip
          path: alt-icons
          retention-days: 2

  patch-wezterm-icon:
    needs:
      - get-wezterm
      - icon-matrix
    env:
      version: ${{ needs.get-wezterm.outputs.version }}
    strategy:
      matrix:
        icon: ${{ fromJson(needs.icon-matrix.outputs.matrix) }}
    runs-on: ubuntu-latest
    steps:
      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: wine64 imagemagick
          version: 1.0

      - uses: actions/download-artifact@v4
        with:
          name: wezterm.zip
          path: wezterm

      - uses: actions/download-artifact@v4
        with:
          name: alt-icons.zip
          path: alt-icons

      - name: "Remote Debugging"
        uses: mxschmitt/action-tmate@v3
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.debugging }}
        with:
          detached: true

      - name: "${{ matrix.icon.file }} → ${{ matrix.icon.ico }}"
        run: |
          export image="${{ matrix.icon.file }}"
          convert -background transparent -define icon:auto-resize="16,32,48,64,96,128,256" "$image" "${{ matrix.icon.ico }}"

      - name: "Create Zip Package with ${{ matrix.icon.ico }}"
        id: zip-windows-package
        run: |          
          # Step 1: Set parameters
          WEZTERM_VERSION="${{ needs.get-wezterm.outputs.version }}"
          ICON_NAME="${{ matrix.icon.name }}"
          RCEDIT_URL="https://github.com/electron/rcedit/releases/download/v2.0.0/rcedit-x64.exe"
          RCEDIT_PATH="$HOME/rcedit-x64.exe"  # Path to store the downloaded rcedit
          NEW_FOLDER_NAME="WezTerm-windows-$ICON_NAME-$WEZTERM_VERSION"
          EXE_PATH="$NEW_FOLDER_NAME/wezterm-gui.exe"
          ICON_PATH="${{ matrix.icon.ico }}"
          
          # Step 2: Download rcedit if it doesn't exist
          if [ ! -f "$RCEDIT_PATH" ]; then
              echo "Downloading rcedit from $RCEDIT_URL"
              curl -L -o "$RCEDIT_PATH" "$RCEDIT_URL"
          else
              echo "rcedit already downloaded."
          fi
          
          # Step 3: Move the wezterm folder into the new folder
          echo "Processing $ICON_NAME..."
          mkdir -p "$NEW_FOLDER_NAME"
          mv wezterm "$NEW_FOLDER_NAME"  # Move the wezterm folder into the new folder
          
          # Step 4: Verify if the target exe exists
          if [ ! -f "$EXE_PATH" ]; then
              echo "Error: Target executable not found: $EXE_PATH"
              exit 1
          fi
          
          # Step 5: Use Wine to patch the executable icon with rcedit
          echo "Patching executable icon using rcedit: $EXE_PATH with icon $ICON_PATH"
          wine "$RCEDIT_PATH" "$EXE_PATH" --set-icon "$ICON_PATH"
          
          # Step 6: Verify if the patch was successful
          if [ $? -eq 0 ]; then
              echo "🎉 Done processing $ICON_NAME."
          else
              echo "❌ Failed to patch icon for $ICON_NAME."
              exit 1
          fi


      - name: "🍹 Upload artifact"
        uses: actions/upload-artifact@v4
        with:
          name: "WezTerm-windows-${{ matrix.icon.name }}-${{ env.version }}.zip"
          path: "WezTerm-windows-${{ matrix.icon.name }}-${{ env.version }}"
          retention-days: 2

