name: WezTerm Windows Alt Icon Builds

on:
  workflow_dispatch:
    inputs:
      debugging:
        type: boolean
        required: false
        default: false

jobs:
  Build-WezTerm-From-Source:

    runs-on: windows-latest
    steps:
      - name: "Checkout Local Repo"
        uses: actions/checkout@v4

      - name: "Remote Debugging"
        uses: mxschmitt/action-tmate@v3
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.debugging }}
        with:
          detached: true

      - name: "Install Dependencies"
        run: |
          choco install imagemagick
          choco install rcedit
          choco install resource-hacker

      - name: "Fetch WezTerm Windows Zip"
        shell: bash
        run: |
          export wezterm_version="$(curl -sv "https://github.com/wezterm/wezterm/releases/latest" 2>&1 \
            | grep -Ei "< Location: https://github.com/wezterm/wezterm/releases/tag/.*$" \
            | sed -e "s|< Location: https://github.com/wezterm/wezterm/releases/tag/||")"
          echo "wezterm_version=$wezterm_version" | tee -a $GITHUB_OUTPUT
          export wezterm_windows_zip_url="https://github.com/wezterm/wezterm/releases/download/${wezterm_version}/WezTerm-windows-${wezterm_version}.zip"

          curl -Lso wezterm_windows.zip "$wezterm_windows_zip_url"

          unzip wezterm_windows.zip

      - name: "Create .ico files"
        run: |
          for image in .alt-icons/*png
          do
            magick -background transparent -define icon:auto-resize="16,24,32,48,64,128,256" "$image" "${image/png/ico}"
          done

      - name: "Copy wezterm_windows.zip for each ico and patch"
        run: |
          echo "TODO"

   #   - name: "Upload artifact"
   #     uses: actions/upload-artifact@v3
   #     with:
   #       name: "windows"
   #       path: |
   #         WezTerm-*.zip
   #       retention-days: 5

