name: WezTerm Windows Alt Icon Builds

on:
  schedule:
    - cron: "0 4 * * *"
  workflow_dispatch:
    inputs:
      debugging:
        type: boolean
        required: false
        default: false

jobs:
  get-wezterm:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get-wezterm-latest.outputs.version }}
    steps:

      - name: Get WezTerm Latest Release Version Tag
        id: get-wezterm-latest
        run: |
          version=$(
            curl -s "https://api.github.com/repos/wezterm/wezterm/releases/latest" \
              | jq -r '.tag_name'
          )

          # Output the tag name using the new syntax
          echo "version=$version" >> $GITHUB_OUTPUT

      - name: Set release tag variable
        id: vars
        run: |
          echo "release_tag=${{ steps.get-wezterm-latest.outputs.version }}-alt-icons" >> $GITHUB_OUTPUT

      - name: Get WezTerm Windows Zip
        id: get-wezterm-zip
        run: |
          export wezterm_version="${{ steps.get-wezterm-latest.outputs.version }}"

          echo "wezterm_version=$wezterm_version"

          export wezterm_folder="WezTerm-windows-${wezterm_version}"
          echo "wezterm_folder=$wezterm_folder"

          export url="https://github.com/wezterm/wezterm/releases/download/${wezterm_version}/${wezterm_folder}.zip"
          echo "url=$url"

          curl -Lso temp.zip "$url"

          unzip temp.zip
          mv $wezterm_folder wezterm
          rm temp.zip

      - name: Debug version capture step one
        run: |
          echo "version: ${{ steps.get-wezterm-latest.outputs.version }}"

      - uses: actions/upload-artifact@v4
        with:
          name: wezterm.zip
          path: wezterm
          retention-days: 2

  icon-matrix:
    needs: get-wezterm
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: "Checkout Local Repo"
        uses: actions/checkout@v4

      - name: Generate Icon Matrix
        id: set-matrix
        run: python3 scripts/generate_icon_matrix.py

      - id: upload-alt-icons
        uses: actions/upload-artifact@v4
        with:
          name: alt-icons.zip
          path: alt-icons
          retention-days: 2

  patch-wezterm-icon:
    needs:
      - get-wezterm
      - icon-matrix
    env:
      version: ${{ needs.get-wezterm.outputs.version }}
    strategy:
      matrix:
        icon: ${{ fromJson(needs.icon-matrix.outputs.matrix) }}
    runs-on: windows-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: wezterm.zip
          path: wezterm

      - uses: actions/download-artifact@v4
        with:
          name: alt-icons.zip
          path: alt-icons

      - name: "Remote Debugging"
        uses: mxschmitt/action-tmate@v3
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.debugging }}
        with:
          detached: true

      - name: "Install Dependencies"
        shell: pwsh
        run: |
          Invoke-RestMethod -Uri https://get.scoop.sh | Invoke-Expression
          scoop install imagemagick rcedit

      - name: "${{ matrix.icon.file }} → ${{ matrix.icon.ico }}"
        shell: bash
        run: |
          export image="${{ matrix.icon.file }}"
          magick -background transparent -define icon:auto-resize="16,32,48,64,96,128,256" "$image" "${{ matrix.icon.ico }}"

      - name: "Create Zip Package with ${{ matrix.icon.ico }}"
        id: zip-windows-package
        shell: pwsh
        run: |
          # Import the wezterm_version from the previous step's output
          $wezterm_version = "${{ needs.get-wezterm.outputs.version }}"
          Write-Host "🖥️ wezterm_version=$wezterm_version"

          $IconName = "${{ matrix.icon.name }}"

          # New folder name combining version and icon part
          $newFolderName = "WezTerm-windows-$IconName-$wezterm_version"

          Write-Host "Processing '$IconName'..."

          Move-Item -Path wezterm -Destination $newFolderName

          $exePath = Join-Path -Path $newFolderName -ChildPath "wezterm-gui.exe"

          Write-Host "Patching executable icon using rcedit: $exePath with icon ${{ matrix.icon.ico }}"
          ~\scoop\shims\rcedit.exe $exePath --set-icon ${{ matrix.icon.ico }}

          Write-Host "🎉 Done processing $IconName."

      - name: "🍹 Upload artifact"
        uses: actions/upload-artifact@v4
        with:
          name: "WezTerm-windows-${{ matrix.icon.name }}-${{ env.version }}.zip"
          path: "WezTerm-windows-${{ matrix.icon.name }}-${{ env.version }}"
          retention-days: 2

