name: WezTerm Windows Alt Icon Builds

on:
  workflow_dispatch:
    inputs:
      debugging:
        type: boolean
        required: false
        default: false

jobs:
  Build-WezTerm-From-Source:

    env:
      BUILD_REASON: "Schedule"
      CARGO_INCREMENTAL: "0"
      SCCACHE_GHA_ENABLED: "true"
      RUSTC_WRAPPER: "sccache"
      RUSTUP_WINDOWS_PATH_ADD_BIN: "1"

    runs-on: windows-latest
    strategy:
      matrix:
        icon:
          - .alt-icons/wezterm-icon-Base.png
          - .alt-icons/wezterm-icon-Shine.png
          - .alt-icons/wezterm-icon-Flatter.png
          - .alt-icons/wezterm-icon-Forest.png

    steps:
      - name: "Checkout Local Repo"
        uses: actions/checkout@v4

      - name: "Install Rust"
        uses: dtolnay/rust-toolchain@stable
        with:
          target: "x86_64-pc-windows-msvc"

      - name: "Compile with sccache"
        uses: mozilla-actions/sccache-action@v0.0.9
        
      - name: "Cache Rust Dependencies"
        uses: actions/cache@v4
        id: cache-cargo-vendor
        with:
          path: |
            vendor
            .cargo/config
          key: "cargo-deps-${{ hashFiles('**/Cargo.lock') }}"

      - name: "Install ripgrep"
        run: |
          cargo install ripgrep

      - name: "Fetch WezTerm Source"
        shell: bash
        run: |
          export wezterm_version="$(curl -sv "https://github.com/wezterm/wezterm/releases/latest" 2>&1 | rg "< location:.*/tag/(.*)$" --replace '$1')"
          echo "wezterm_version=$wezterm_version" >> $GITHUB_OUTPUT
          export wezterm_src_tar_url="https://github.com/wezterm/wezterm/releases/download/${wezterm_version}/wezterm-${wezterm_version}-src.tar.gz"
          echo "$wezterm_src_tar_url"
          curl -Lso wezterm_source.tar.gz "$wezterm_src_tar_url"
          tar xf wezterm_source.tar.gz
          mv -v "wezterm-${wezterm_version}"/* . # Move files to pwd


          # inspect and salvage wezterm/wezterm .github path
          if [[ -d "wezterm-${wezterm_version}"/.github ]]; then
            ls -lahFr "wezterm-${wezterm_version}"/.github
          else
            cat "wezterm-${wezterm_version}"/.github
          fi
          # save as .github-wezterm-source
          mv "wezterm-${wezterm_version}"/.github ./.github-wezterm-source


          mv -v "wezterm-${wezterm_version}"/.* . # Move dotfiles to pwd
          rm -rf "wezterm-${wezterm_version}"
          ls -lahF

      - name: "Remote Debugging"
        uses: mxschmitt/action-tmate@v3
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.debugging }}

      - name: "Vendor dependecies"
        if: steps.cache-cargo-vendor.outputs.cache-hit != 'true'
        shell: bash
        run: |
          cargo vendor --locked --versioned-dirs >> .cargo\config

      - name: "Replace terminal.ico"
        run: |
          magick -define icon:auto-resize=512,256,128,64,48 ${{ matrix.icon }} assets/Windows/terminal.ico

      - name: "Build WezTerm"
        shell: cmd
        run: |
          SET PATH=C:\Strawberry\perl\bin;%PATH%
          cargo update
          cargo build -p wezterm --release
          cargo build -p wezterm-gui --release
          cargo build -p wezterm-mux-server --release
          cargo build -p strip-ansi-escapes --release

      - name: "Review Build"
        shell: bash
        run: |
          echo "- - -"
          find . | grep -E "(zip|exe)"

      - name: "Run ci/deploy.sh"
        shell: bash
        run: |
          ci/deploy.sh


   #   - name: "Upload artifact"
   #     uses: actions/upload-artifact@v3
   #     with:
   #       name: "windows"
   #       path: |
   #         WezTerm-*.zip
   #         WezTerm-*.exe
   #       retention-days: 5

