name: WezTerm Windows alt icons builds

on:
  workflow_dispatch:

jobs:
  Build-WezTerm-From-Source:

    env:
      BUILD_REASON: "Schedule"
      CARGO_INCREMENTAL: "0"
      SCCACHE_GHA_ENABLED: "true"
      RUSTC_WRAPPER: "sccache"
      RUSTUP_WINDOWS_PATH_ADD_BIN: "1"

    runs-on: windows-latest
    strategy:
      matrix:
        icon:
          - .alt-icons/wezterm-icon-Base.png
          - .alt-icons/wezterm-icon-Shine.png
          - .alt-icons/wezterm-icon-Flatter.png
          - .alt-icons/wezterm-icon-Forest.png

    steps:
      - name: "checkout repo"
        uses: actions/checkout@v4

      - name: "Install Rust"
        uses: dtolnay/rust-toolchain@stable
        with:
          target: "x86_64-pc-windows-msvc"

      - name: "Compile with sccache"
        uses: mozilla-actions/sccache-action@v0.0.9

      - name: "Cache Rust Dependencies"
        uses: actions/cache@v4
        id: cache-cargo-vendor
        with:
          path: |
            vendor
            .cargo/config
          key: "cargo-deps-${{ hashFiles('**/Cargo.lock') }}"

      - name: fetch source
        shell: bash
        run: |
          export wezterm_version="$(curl -sv "https://github.com/wezterm/wezterm/releases/latest" 2>&1 \
            | grep -Ei "< Location: https://github.com/wezterm/wezterm/releases/tag/.*$" \
            | sed -e "s|< Location: https://github.com/wezterm/wezterm/releases/tag/||")"
          echo "wezterm_version=$wezterm_version" >> $GITHUB_OUTPUT
          curl -Lso wezterm_source.tar.gz "https://github.com/wezterm/wezterm/archive/refs/tags/${wezterm_version}.tar.gz"
          tar xf wezterm_source.tar.gz
          mv "wezterm-${wezterm_version}"/* ~/
          rm -rf "wezterm-${wezterm_version}"

      - name: "Vendor dependecies"
        if: steps.cache-cargo-vendor.outputs.cache-hit != 'true'
        shell: bash
        run: |
          cargo vendor --locked --versioned-dirs >> ~/.cargo/config

      - name: Replace terminal.ico
        run: |
          magick -define icon:auto-resize=512,256,128,64,48 ${{ matrix.icon }} assets/Windows/terminal.ico

      - name: build wezterm
        shell: cmd
        run: |
          SET PATH=C:\Strawberry\perl\bin;%PATH%
          cargo build -p wezterm --release
          cargo build -p wezterm-gui --release
          cargo build -p wezterm-mux-server --release
          cargo build -p strip-ansi-escapes --release
          cargo nextest run --all --no-fail-fast

      - name: ci deploy
        shell: bash
        run: |
          ci/deploy.sh

      - name: review
        shell: bash
        run: |
          ls -lahF
          echo "- - -"
          find . | grep -E "(zip|exe)"

      - name: "Upload artifact"
        uses: actions/upload-artifact@v3
        with:
          name: "windows"
          path: |
            WezTerm-*.zip
            WezTerm-*.exe
          retention-days: 5

