name: WezTerm Windows Alt Icon Builds

on:
  workflow_dispatch:
    inputs:
      debugging:
        type: boolean
        required: false
        default: false

jobs:
  Build-WezTerm-From-Source:

    env:
      BUILD_REASON: "Schedule"
      CARGO_INCREMENTAL: "0"
      SCCACHE_GHA_ENABLED: "true"
      RUSTC_WRAPPER: "sccache"
      RUSTUP_WINDOWS_PATH_ADD_BIN: "1"

    runs-on: windows-latest
    strategy:
      matrix:
        icon:
          - .alt-icons/wezterm-icon-Base.png
          - .alt-icons/wezterm-icon-Shine.png
          - .alt-icons/wezterm-icon-Flatter.png
          - .alt-icons/wezterm-icon-Forest.png

    steps:
      - name: "Checkout Local Repo"
        uses: actions/checkout@v4

      - name: "Remote Debugging"
        uses: mxschmitt/action-tmate@v3
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.debugging }}
        with:
          detached: true

      - name: "Install Dependencies"
        run: |
          choco install imagemagick
          choco install rcedit
          choco install resource-hacker

      - name: "Fetch WezTerm Windows Zip"
        shell: bash
        run: |
          export wezterm_version="$(curl -sv "https://github.com/wezterm/wezterm/releases/latest" 2>&1 \
            | grep -Ei "< Location: https://github.com/wezterm/wezterm/releases/tag/.*$" \
            | sed -e "s|< Location: https://github.com/wezterm/wezterm/releases/tag/||")"
          echo "wezterm_version=$wezterm_version" | tee -a $GITHUB_OUTPUT
          export wezterm_windows_zip_url="https://github.com/wezterm/wezterm/releases/download/${wezterm_version}/WezTerm-windows-${wezterm_version}.zip"

          curl -Lso wezterm_windows.zip "$wezterm_windows_zip_url"

          unzip wezterm_windows.zip

      - name: "Replace terminal.ico"
        run: |
          magick -define icon:auto-resize=512,256,128,64,48 ${{ matrix.icon }} terminal.ico

   #   - name: "Upload artifact"
   #     uses: actions/upload-artifact@v3
   #     with:
   #       name: "windows"
   #       path: |
   #         WezTerm-*.zip
   #         WezTerm-*.exe
   #       retention-days: 5

