name: Get WezTerm Source from nightly buils

on:
  workflow_dispatch:

jobs:
  check:
    runs-on: windows-latest
    steps:
      - name: fetch source
        shell: bash
        run: |
          curl -sv https://github.com/wezterm/wezterm/releases/latest

          echo "Extracting Version"
          
          export wezterm_version="$(curl -sv "https://github.com/wezterm/wezterm/releases/latest" 2>&1 \
            | grep -Ei "< Location: https://github.com/wezterm/wezterm/releases/tag/.*$" \
            | sed -e "s|< Location: https://github.com/wezterm/wezterm/releases/tag/||")"

          echo "wezterm_version=$wezterm_version" >> $GITHUB_OUTPUT
          echo "Get source"
          echo "https://github.com/wezterm/wezterm/archive/refs/tags/${wezterm_version}.tar.gz"
          curl -Lsvo wezterm_source.tar.gz "https://github.com/wezterm/wezterm/archive/refs/tags/${wezterm_version}.tar.gz"
          ls -lah .
          
          tar xvf wezterm_source.tar.gz
          echo "--- WezTerm ls recursive ($wezterm_version)"
          ls -lahR .
