name: Create Release from Windows Artifacts

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

on:
  workflow_run:
    workflows: ["WezTerm Windows Alt Icon Builds"]
    types: [completed]

jobs:
  # Check if early exit is needed
  check_upstream:
    runs-on: ubuntu-latest
    outputs:
      early_exit: ${{ steps.set_early_exit.outputs.early_exit }}
    steps:
      - uses: actions/checkout@v4

      - name: Upstream Summary
        run: |
          echo "👉  Upstream conclusion: ${CONCLUSION-Unknown}"
          if [ "$CONCLUSION" != "success" ]; then
            echo "🤷 Upstream did not succeed. Early exit." | tee -a $GITHUB_STEP_SUMMARY
            echo "early_exit=true" >> $GITHUB_OUTPUT
            exit 1  # This will stop further jobs
          else
            echo "🚀 Upstream ok..." | tee -a $GITHUB_STEP_SUMMARY
            echo "early_exit=false" >> $GITHUB_OUTPUT
          fi

  # Job to handle release tag and assets comparison
  release_logic:
    runs-on: ubuntu-latest
    needs: check_upstream
    if: ${{ needs.check_upstream.outputs.early_exit == 'false' }}  # Proceed only if no early exit
    steps:
      - uses: actions/checkout@v4

      - name: Get latest wezterm tag
        id: wezterm_tag
        run: |
          tag=$(gh api repos/wezterm/wezterm/releases/latest --jq .tag_name)
          echo "WezTerm Release Tag: $tag" | tee -a $GITHUB_STEP_SUMMARY
          echo "tag=$tag" >> $GITHUB_OUTPUT

      - name: Set release tag variable
        id: set_release_tag
        run: |
          export release_tag=${{ steps.wezterm_tag.outputs.tag }}-alt-icons
          echo "release_tag=$release_tag" >> $GITHUB_ENV
          echo "Internal Release Tag: $release_tag" | tee -a $GITHUB_STEP_SUMMARY

      - name: Check if release tag exists
        id: check_tag
        run: |
          echo "Checking for tag '${release_tag}' via GitHub API..." | tee -a $GITHUB_STEP_SUMMARY
          tags_json=$(gh api repos/${{ github.repository }}/releases --jq '.[].tag_name')

          if [[ -z "$tags_json" || ! "${tags_json}" == *"${release_tag}"* ]]; then
            echo "No existing release tag, creating new release." | tee -a $GITHUB_STEP_SUMMARY
            echo "exists=false" >> $GITHUB_OUTPUT
          else
            echo "Existing release tag found: $release_tag" | tee -a $GITHUB_STEP_SUMMARY
            echo "exists=true" >> $GITHUB_OUTPUT
          fi

      - name: Check Existing Release Assets
        if: ${{ steps.check_tag.outputs.exists == 'true' }}
        id: compare_assets
        run: |
          gh api repos/${{ github.repository }}/releases/tags/${release_tag} --jq '.assets[] | .name' > assets.list
          gh api repos/${{ github.repository }}/actions/runs/${BUILD_ID}/artifacts --jq '.artifacts[] | .name' | grep -E -v '(alt-icons[.]zip|wezterm[.]zip)' > artifacts.list

          # Compare asset names with artifact names
          cat <<EOD | tee -a $GITHUB_STEP_SUMMARY
          ### Existing Release Assets
          $(< assets.list)

          ### Artifacts from Triggering Workflow
          $(< artifacts.list)
          EOD

          if [ "$(wc -l < artifacts.list)" -eq "$(wc -l < assets.list)" ]; then
            # Compare names (not content) of assets and artifacts
            if diff <(sort assets.list) <(sort artifacts.list); then
              echo "identical=true" >> $GITHUB_OUTPUT
            else
              echo "identical=false" >> $GITHUB_OUTPUT
              echo "⚠️ New artifacts found, release needs update." | tee -a $GITHUB_STEP_SUMMARY
            fi
          else
            echo "identical=false" >> $GITHUB_OUTPUT
            echo "⚠️ New artifacts found, release needs update." | tee -a $GITHUB_STEP_SUMMARY
          fi

  # Handle the release process if assets need updating
  release_process:
    runs-on: ubuntu-latest
    needs: release_logic
    if: ${{ needs.release_logic.outputs.identical == 'false' }}  # Proceed only if assets are different
    steps:
      - uses: actions/checkout@v4

      - name: Generate release notes
        run: |
          python3 scripts/generate_release_notes.py > RELEASE.md

      - name: Append to SHIPPED.log.md
        run: |
          datetime=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
          echo "- shipped: $datetime - $release_tag"  >> SHIPPED.log.md
          
          git config user.name "alt-icons-actions"
          git config user.email "alt-icons@into.the.void"
          git add SHIPPED.log.md
          git commit -m "Shipped WezTerm Windows $release_tag ${datetime}"
          git push

  # Create or move the release tag on the latest commit
  create_or_move_tag:
    runs-on: ubuntu-latest
    needs: release_process
    if: ${{ needs.release_process.outputs.identical == 'false' }}  # Only run if release process happens
    steps:
      - uses: actions/checkout@v4

      - name: Create or move release tag on latest commit
        run: |
          git tag --force "$release_tag"
          git push --tags --force

  # Job to upload artifacts to the release
  upload_artifacts:
    runs-on: ubuntu-latest
    needs: create_or_move_tag
    if: ${{ needs.create_or_move_tag.outputs.identical == 'false' }}  # Proceed only if tag creation happened
    steps:
      - uses: actions/checkout@v4

      - name: Upload artifacts to release
        run: |
          for artifact in artifacts/*.zip; do
            artifact_name=$(basename "$artifact")
            exists=$(echo "${{ steps.compare_assets.outputs.assets_list }}" | grep -q "^${artifact_name}$"; echo $?)
            if [ $exists -ne 0 ]; then
              gh release upload "$release_tag" "$artifact"
            fi
          done
