name: Get WezTerm Source from nightly buils

on:
  workflow_dispatch:

jobs:
  fetch-wezterm-tar-gz:
    runs-on: windows-latest
    steps:
      - name: fetch source
        shell: bash
        run: |
          export wezterm_version="$(curl -sv "https://github.com/wezterm/wezterm/releases/latest" 2>&1 \
            | grep -Ei "< Location: https://github.com/wezterm/wezterm/releases/tag/.*$" \
            | sed -e "s|< Location: https://github.com/wezterm/wezterm/releases/tag/||")"
          echo "wezterm_version=$wezterm_version" >> $GITHUB_OUTPUT
          curl -Lso wezterm_source.tar.gz "https://github.com/wezterm/wezterm/archive/refs/tags/${wezterm_version}.tar.gz"
          tar xvf wezterm_source.tar.gz
          mv "wezterm-${wezterm_version}" wezterm
          echo "--- WezTerm assets/Windows ($wezterm_version)"
          ls -lahF wezterm/assets/Windows
