name: Workflow Keepalive

on:
  schedule:
    - cron: '0 0 1 */2 *'
  workflow_dispatch:
    inputs:
      reason:
        description: Manual trigger reason
        required: false
        default: Maintenance

env:
  THRESHOLD_DAYS: 45
  GIT_ID: github-actions
  GIT_EMAIL: github-actions[bot]@users.noreply.github.com

jobs:
  keepalive:
    name: 🔵 Pulse Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Calculate Inactivity
        id: timekeeper
        run: |
          LAST_COMMIT_EPOCH=$(git log -1 --format=%ct)
          CURRENT_EPOCH=$(date +%s)
          INACTIVE_DAYS=$(( (CURRENT_EPOCH - LAST_COMMIT_EPOCH) / 86400 ))
          echo "inactive_days=$INACTIVE_DAYS" >> $GITHUB_OUTPUT
          echo "last_commit_date=$(date -d @$LAST_COMMIT_EPOCH '+%Y-%m-%d')" >> $GITHUB_OUTPUT

      - name: Set Reason
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ] \
                && [ -n "${{ github.event.inputs.reason }}" ]
          then
            echo "REASON=${{ github.event.inputs.reason }}" >> $GITHUB_ENV
          else
            echo "REASON=Scheduled" >> $GITHUB_ENV
          fi

      - name: Conditional Keepalive
        if: ${{ fromJson(steps.timekeeper.outputs.inactive_days) > fromJson(env.THRESHOLD_DAYS) }}
        run: |
          git config user.name "$GIT_ID"
          git config user.email "$GIT_EMAIL"
          git commit --allow-empty \
            -m "Keepalive (inactive ${INACTIVE_DAYS}d) [skip ci]" \
            -m "Triggered: ${REASON}"$'\n'"Repo age: ${LAST_COMMIT_DATE}"

          git push

      - name: ✅ Status Report
        run: |
          echo "=== Keepalive Report ==="
          echo "Last commit: ${{ steps.timekeeper.outputs.last_commit_date }}"
          echo "Inactive days: ${{ steps.timekeeper.outputs.inactive_days }}/$THRESHOLD_DAYS"
          echo "Action taken: ${{ steps.timekeeper.outputs.inactive_days > env.THRESHOLD_DAYS && 'Commit pushed' || 'No action needed' }}"
